idiomsapp/urls.py
__author__ = 'Lenovo'
from django.conf.urls import url,include
from django.contrib import admin
from django.core.urlresolvers import reverse
import views
from django.conf.urls import url

from . import views

app_name = 'idiomsapp'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^idioms', views.idiomsPost, name='idioms'),
    url(r'^haha', views.result, name = 'result')
    # url(r'^write', views.write, name='write'),
]

idiomsapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Idioms(models.Model):
    idiom = models.CharField(max_length = 200);
    level = models.IntegerField();

    def __str__(self):              # __unicode__ on Python 2
        return self.idiom

idiomsapp/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.core.urlresolvers import reverse
from idiomsapp.models import *
from django.views.decorators.csrf import csrf_exempt

import pandas as pd
import os
# Create your views here.
def home(request):
    return render(request, 'Home.html', {})

def idiomsPost(request):
    context={}
    level =  int(request.POST['diff'])
    idioms = Idioms.objects.filter(level = level).order_by('?')
    context['idioms'] = idioms[:50]
    context['first_idiom'] = idioms[51]
    return render(request, 'IdiomsPost.html', context)

@csrf_exempt
def result(request):
    context = {}
    context ['wrongIdioms']  = request.POST['wrongIdioms']
    context ['tick'] = request.POST['tick']
    print context['tick']
    print context['wrongIdioms']
    return render(request, 'result.html', context)


# def write(request):
#     dir_path = os.path.dirname(os.path.realpath(__file__))
#     paths = dir_path+"/static/idioms_with_levels.csv"
#     idioms = pd.read_csv(paths)
#     idioms_junior = idioms[idioms["level"] == 3]["idioms"]
#     idioms_middle = idioms[idioms["level"] == 2]["idioms"]
#     for id in idioms_junior:
#         id_temp = id.replace("\r\n","").decode("utf-8-sig")
#         idiom = Idioms(idiom=id_temp,level=3)
#         idiom.save()
#     print a
#     return render(request, 'IdiomsPost.html', {})

idiomsapp/templates/Home.html
<!DOCTYPE html>
<html lang="ch">
<head>
    <meta charset="UTF-8">
    <title>IdiomsHomePage</title>
    {% load static %}
    <link href=" {% static 'css/buttons.css' %}" rel = "stylesheet">

</head>
<body>
    <div class="container">
        <form  method="post" action = "{% url 'idiomsapp:idioms'%}">
            {% csrf_token %}
            <big><big><h2 text-align = 'center'>中国成语大会现场</h2></big></big>
            <ul>
                <li>
                  <input type="radio" id="easy" name="diff" value="1" checked/>
                  <label for="easy">小学生</label>
                  <div class="check"></div>
                </li>

                <li>
                  <input type="radio" id="middle" name="diff" value="2">
                  <label for="middle">初中生</label>
                  <div class="check"><div class="inside"></div></div>
                </li>

                <li>
                  <input type="radio" id="difficult" name="diff" value="3">
                  <label for="difficult">高中生</label>
                  <div class="check"><div class="inside"></div></div>
                </li>
             </ul>
                <div align = "center">
                    <button id="submit" class="submit"  align = "right" >战</button>
                </div>
        </form>
  </div>

</body>
</html>


idiomsapp/templates/IdiomsPost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IdiomsGuess</title>
    {% load static %}
    <link href=" {% static 'css/guess.css' %}" rel = "stylesheet">
    <link href=" {% static 'css/buttons.css' %}" rel = "stylesheet">
    <script src = "{% static 'js/jquery.js' %}"></script>

</head>
<body>

    <div class="idiomsHolder" align = "center">
        <h1> <big><big>
            <ul class = "idioms"> {{first_idiom.idiom}}</ul>
            {% for idiom in idioms %}
               <ul class = "idioms" hidden>{{ idiom.idiom }}</ul>
            {% endfor %}
        </big></big>  </h1>
    </div>
    <div>
    <table align = "right" width = 70%>
        <tr>
            <td>
                <div id="countdown"></div>
            </td>
            <td>
               <div class="buttonHolder">
                    <a href="#" class="button tick" id = "tick"></a>
                    <a href="#" class="button cross" id = "cross"></a>
                    <div class = "result" hidden>
                             <h1>战绩: </h1>
                    </div>
                    <div class = "restart" hidden>

                         <form  method="post" action = "{% url 'idiomsapp:home'%}">
                             {% csrf_token %}

                             <div>
                                <button id="submit" class="submit"  align = "center">再战</button>
                              </div>
                        </form>
                    </div>
                </div>
            </td>
        </tr>
    </table>
    </div>
</body>

<script src = "{% static 'js/guess.js' %}"></script>
</html>